---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# crbiodiversity

<!-- badges: start -->
<!-- badges: end -->

The goal of crbiodiversity is to searching and retrieving biodiversity data of Costa Rica

## Installation

You can install the development version of **crbiodiversity** like so:

``` r
# install.packages("devtools")
devtools::install_github("ManuelSpinola/crbiodiversity")
```
Also you need to install the following packages:

``` r
# install.packages("devtools")
devtools::install_github("ManuelSpinola/crgeo")
```

``` r
# install.packages("devtools")
devtools::install_github("ManuelSpinola/crgrids")
```

## Example

This is a basic example how to use the package:

```{r example, message = FALSE, warning=FALSE}
library(tidyverse)
library(spocc)
library(sf)
library(crgeo)
library(crgrids)
library(crbiodiversity)
```


```{r}
loc <- get_locations("Agalychnis callidryas")
```


```{r}
head(loc)
```


```{r}
get_map("Agalychnis callidryas")
```





